version: '3.8'

services:
  app:
    build: .
    container_name: api_livros_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - api_livros_net

  db:
    image: mysql:8.0
    container_name: api_livros_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_livros
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_livros_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api_livros_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - api_livros_net

volumes:
  db_data:

networks:
  api_livros_net: